"""empty message

Revision ID: 424d541f526f
Revises: 0c52941a5ffd
Create Date: 2022-03-07 03:01:14.000047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424d541f526f'
down_revision = '0c52941a5ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name'),
    sa.UniqueConstraint('group_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
