"""empty message

Revision ID: b1630a717719
Revises: 424d541f526f
Create Date: 2022-03-07 03:05:38.845125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1630a717719'
down_revision = '424d541f526f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('contacts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'contacts')
    # ### end Alembic commands ###
